Fixed bug in filesystem with file path searching
Bug was introduced with b83da985d10a1c085e30aaa08536aed022b06182

This commit fixes possible issues with file path search and, in
particular, crash in Clear Sky with log:
ERROR: There are no sound collection with path:
characters_voice\scenario\agroprom\agr_base_commander_reward_pda

This is another 3 year old bug!!!
Those "refactoring" commits made by me in 2017-2018 should be totally
reviewed!